version: '2'
services:
  glam:
    ports:
      - "8050:8050"
    image: quay.io/fhcrc-microbiome/glam-browser-v2:latest

    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - S3_BUCKET
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - REDIS_URL="redis://redis:6379"

  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
