name: Test Indexing

on: [push, pull_request]  

jobs:

  testGlamDB:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: testAdmin
          MYSQL_PASSWORD: testPassword
          MYSQL_DATABASE: glamDB
          MYSQL_ROOT_PASSWORD: rootPassword
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    env:
      DB_NAME: 'glamDB'
      DB_USERNAME: 'testAdmin'
      DB_PASSWORD: 'testPassword'
      DB_HOST: 'localhost'
    steps:
      - name: Set up Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name:  Checkout repository
        uses: actions/checkout@v1
      - name: Install GLAM CLI
        run: |        
          python3 -m pip install setuptools
          python3 -m pip install wheel
          python3 -m pip install .
      - name:  Set up database
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          mysqld_safe
          glam-cli setup
          glam-cli add-user --username testUser --email testUser@email.com
          glam-cli set-password --username testUser --password testUserPassword
          glam-cli add-dataset --dataset-id dataset_id --name dataset_name --uri s3://glam-datasets/dataset_id/
          glam-cli grant-access --user testUser --dataset dataset_id
