name: Test Indexing

on: [push, pull_request]  

jobs:

  testGlamDB:
    runs-on: ubuntu-latest
    env:
      DB_NAME: 'glamDB'
      DB_USERNAME: 'testAdmin'
      DB_PASSWORD: 'testPassword'
      DB_HOST: 'localhost'
      DB_PORT: 3800
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: |
          docker build -t glam .
      - name:  Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: 'latest' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'test' # Optional, default value is "test". The specified database which will be create
          mysql user: 'testAdmin' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'testPassword' # Required if "mysql user" exists. The password for the "mysql user"
      - name:  Set up database
        run: |
          docker run glam cli.py setup
          docker run glam cli.py add-user --username testUser --email testUser@email.com
          docker run glam cli.py set-password --username testUser --password testUserPassword
          docker run glam cli.py add-dataset --dataset-id dataset_id --name dataset_name --uri s3://glam-datasets/dataset_id/
          docker run glam cli.py grant-access --user testUser --dataset dataset_id
